baseURL: "http://example.org/"
languangeCode: "en-us"
title: "Japodhi's Blog"
theme: "japodhi"

params:
  description: "Japodhi is writing computer programs."
  links:
  - github: "https://github.com/japodhidev/"
    twitter: "https://twitter.com/japodhi_dev/"
    linkedin: "https://www.linkedin.com/in/finch-ochieng/"
    archive: "https://bitbucket.org/japodhidev/"

menu:
  main:
  - name: "Home"
    pre: "home"
    url: "/"
    weight: 1
  - name: "Posts"
    pre: "pen-tool"
    url: "/posts/"
    weight: 2
  - name: "About"
    pre: "info"
    url: "/about/"
    weight: 3

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_lines: ""
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4